const employeeJSON = [
  {
    id: 1,
    firstname: "Rosanne",
    lastname: "Fancie",
    email: "Rosanne.Fancie@yopmail.com",
    email2: "Rosanne.Fancie@gmail.com",
    profession: "firefighter",
  },
  {
    id: 2,
    firstname: "Elsie",
    lastname: "Mathilde",
    email: "Elsie.Mathilde@yopmail.com",
    email2: "Elsie.Mathilde@gmail.com",
    profession: "firefighter",
  },
  {
    id: 3,
    firstname: "Britni",
    lastname: "Si",
    email: "Britni.Si@yopmail.com",
    email2: "Britni.Si@gmail.com",
    profession: "police officer",
  },
  {
    id: 4,
    firstname: "Brynna",
    lastname: "Warthman",
    email: "Brynna.Warthman@yopmail.com",
    email2: "Brynna.Warthman@gmail.com",
    profession: "worker",
  },
  {
    id: 5,
    firstname: "Nessie",
    lastname: "Septima",
    email: "Nessie.Septima@yopmail.com",
    email2: "Nessie.Septima@gmail.com",
    profession: "doctor",
  },
  {
    id: 6,
    firstname: "Tina",
    lastname: "Rona",
    email: "Tina.Rona@yopmail.com",
    email2: "Tina.Rona@gmail.com",
    profession: "developer",
  },
  {
    id: 7,
    firstname: "Dania",
    lastname: "Thad",
    email: "Dania.Thad@yopmail.com",
    email2: "Dania.Thad@gmail.com",
    profession: "firefighter",
  },
  {
    id: 8,
    firstname: "Genevra",
    lastname: "Susannah",
    email: "Genevra.Susannah@yopmail.com",
    email2: "Genevra.Susannah@gmail.com",
    profession: "police officer",
  },
  {
    id: 9,
    firstname: "Ivett",
    lastname: "Alexandr",
    email: "Ivett.Alexandr@yopmail.com",
    email2: "Ivett.Alexandr@gmail.com",
    profession: "police officer",
  },
  {
    id: 10,
    firstname: "Mady",
    lastname: "Chrystel",
    email: "Mady.Chrystel@yopmail.com",
    email2: "Mady.Chrystel@gmail.com",
    profession: "doctor",
  },
  {
    id: 11,
    firstname: "Belinda",
    lastname: "Anderea",
    email: "Belinda.Anderea@yopmail.com",
    email2: "Belinda.Anderea@gmail.com",
    profession: "worker",
  },
  {
    id: 12,
    firstname: "Kristan",
    lastname: "Gavrila",
    email: "Kristan.Gavrila@yopmail.com",
    email2: "Kristan.Gavrila@gmail.com",
    profession: "firefighter",
  },
  {
    id: 13,
    firstname: "Antonietta",
    lastname: "Nance",
    email: "Antonietta.Nance@yopmail.com",
    email2: "Antonietta.Nance@gmail.com",
    profession: "doctor",
  },
  {
    id: 14,
    firstname: "Carmela",
    lastname: "Jefferey",
    email: "Carmela.Jefferey@yopmail.com",
    email2: "Carmela.Jefferey@gmail.com",
    profession: "developer",
  },
  {
    id: 15,
    firstname: "Ebonee",
    lastname: "Shields",
    email: "Ebonee.Shields@yopmail.com",
    email2: "Ebonee.Shields@gmail.com",
    profession: "firefighter",
  },
  {
    id: 16,
    firstname: "Allis",
    lastname: "Norvol",
    email: "Allis.Norvol@yopmail.com",
    email2: "Allis.Norvol@gmail.com",
    profession: "police officer",
  },
  {
    id: 17,
    firstname: "Mireielle",
    lastname: "Ahab",
    email: "Mireielle.Ahab@yopmail.com",
    email2: "Mireielle.Ahab@gmail.com",
    profession: "doctor",
  },
  {
    id: 18,
    firstname: "Tracey",
    lastname: "Laverne",
    email: "Tracey.Laverne@yopmail.com",
    email2: "Tracey.Laverne@gmail.com",
    profession: "doctor",
  },
  {
    id: 19,
    firstname: "Robinia",
    lastname: "Autrey",
    email: "Robinia.Autrey@yopmail.com",
    email2: "Robinia.Autrey@gmail.com",
    profession: "police officer",
  },
  {
    id: 20,
    firstname: "Imojean",
    lastname: "Alarise",
    email: "Imojean.Alarise@yopmail.com",
    email2: "Imojean.Alarise@gmail.com",
    profession: "police officer",
  },
  {
    id: 21,
    firstname: "Basia",
    lastname: "Leler",
    email: "Basia.Leler@yopmail.com",
    email2: "Basia.Leler@gmail.com",
    profession: "developer",
  },
  {
    id: 22,
    firstname: "Maryellen",
    lastname: "Kylander",
    email: "Maryellen.Kylander@yopmail.com",
    email2: "Maryellen.Kylander@gmail.com",
    profession: "police officer",
  },
  {
    id: 23,
    firstname: "Rivalee",
    lastname: "Heidt",
    email: "Rivalee.Heidt@yopmail.com",
    email2: "Rivalee.Heidt@gmail.com",
    profession: "firefighter",
  },
  {
    id: 24,
    firstname: "Barbi",
    lastname: "Shanley",
    email: "Barbi.Shanley@yopmail.com",
    email2: "Barbi.Shanley@gmail.com",
    profession: "doctor",
  },
  {
    id: 25,
    firstname: "Lilith",
    lastname: "Old",
    email: "Lilith.Old@yopmail.com",
    email2: "Lilith.Old@gmail.com",
    profession: "developer",
  },
  {
    id: 26,
    firstname: "Caressa",
    lastname: "Rolf",
    email: "Caressa.Rolf@yopmail.com",
    email2: "Caressa.Rolf@gmail.com",
    profession: "developer",
  },
  {
    id: 27,
    firstname: "Misha",
    lastname: "Toni",
    email: "Misha.Toni@yopmail.com",
    email2: "Misha.Toni@gmail.com",
    profession: "doctor",
  },
  {
    id: 28,
    firstname: "Elena",
    lastname: "Douglass",
    email: "Elena.Douglass@yopmail.com",
    email2: "Elena.Douglass@gmail.com",
    profession: "firefighter",
  },
  {
    id: 29,
    firstname: "Liana",
    lastname: "Kiersten",
    email: "Liana.Kiersten@yopmail.com",
    email2: "Liana.Kiersten@gmail.com",
    profession: "police officer",
  },
  {
    id: 30,
    firstname: "Tera",
    lastname: "Dalli",
    email: "Tera.Dalli@yopmail.com",
    email2: "Tera.Dalli@gmail.com",
    profession: "police officer",
  },
  {
    id: 31,
    firstname: "Catrina",
    lastname: "Behre",
    email: "Catrina.Behre@yopmail.com",
    email2: "Catrina.Behre@gmail.com",
    profession: "police officer",
  },
  {
    id: 32,
    firstname: "Carmela",
    lastname: "Douglass",
    email: "Carmela.Douglass@yopmail.com",
    email2: "Carmela.Douglass@gmail.com",
    profession: "worker",
  },
  {
    id: 33,
    firstname: "Kathy",
    lastname: "Sidonius",
    email: "Kathy.Sidonius@yopmail.com",
    email2: "Kathy.Sidonius@gmail.com",
    profession: "worker",
  },
  {
    id: 34,
    firstname: "Nerta",
    lastname: "Monk",
    email: "Nerta.Monk@yopmail.com",
    email2: "Nerta.Monk@gmail.com",
    profession: "doctor",
  },
  {
    id: 35,
    firstname: "Shirlee",
    lastname: "Mata",
    email: "Shirlee.Mata@yopmail.com",
    email2: "Shirlee.Mata@gmail.com",
    profession: "police officer",
  },
  {
    id: 36,
    firstname: "Joane",
    lastname: "Tybald",
    email: "Joane.Tybald@yopmail.com",
    email2: "Joane.Tybald@gmail.com",
    profession: "police officer",
  },
  {
    id: 37,
    firstname: "Flo",
    lastname: "Sheedy",
    email: "Flo.Sheedy@yopmail.com",
    email2: "Flo.Sheedy@gmail.com",
    profession: "doctor",
  },
  {
    id: 38,
    firstname: "Concettina",
    lastname: "Libna",
    email: "Concettina.Libna@yopmail.com",
    email2: "Concettina.Libna@gmail.com",
    profession: "firefighter",
  },
  {
    id: 39,
    firstname: "Petronia",
    lastname: "Middleton",
    email: "Petronia.Middleton@yopmail.com",
    email2: "Petronia.Middleton@gmail.com",
    profession: "firefighter",
  },
  {
    id: 40,
    firstname: "Sissy",
    lastname: "Sammons",
    email: "Sissy.Sammons@yopmail.com",
    email2: "Sissy.Sammons@gmail.com",
    profession: "police officer",
  },
  {
    id: 41,
    firstname: "Paulita",
    lastname: "Isidore",
    email: "Paulita.Isidore@yopmail.com",
    email2: "Paulita.Isidore@gmail.com",
    profession: "worker",
  },
  {
    id: 42,
    firstname: "Deedee",
    lastname: "Raychel",
    email: "Deedee.Raychel@yopmail.com",
    email2: "Deedee.Raychel@gmail.com",
    profession: "worker",
  },
  {
    id: 43,
    firstname: "Cathyleen",
    lastname: "Ivens",
    email: "Cathyleen.Ivens@yopmail.com",
    email2: "Cathyleen.Ivens@gmail.com",
    profession: "developer",
  },
  {
    id: 44,
    firstname: "Kaia",
    lastname: "Adlare",
    email: "Kaia.Adlare@yopmail.com",
    email2: "Kaia.Adlare@gmail.com",
    profession: "worker",
  },
  {
    id: 45,
    firstname: "Romona",
    lastname: "Rossner",
    email: "Romona.Rossner@yopmail.com",
    email2: "Romona.Rossner@gmail.com",
    profession: "worker",
  },
  {
    id: 46,
    firstname: "Fanny",
    lastname: "Faro",
    email: "Fanny.Faro@yopmail.com",
    email2: "Fanny.Faro@gmail.com",
    profession: "worker",
  },
  {
    id: 47,
    firstname: "Genovera",
    lastname: "Hamil",
    email: "Genovera.Hamil@yopmail.com",
    email2: "Genovera.Hamil@gmail.com",
    profession: "developer",
  },
  {
    id: 48,
    firstname: "Randa",
    lastname: "Maribeth",
    email: "Randa.Maribeth@yopmail.com",
    email2: "Randa.Maribeth@gmail.com",
    profession: "worker",
  },
  {
    id: 49,
    firstname: "Claresta",
    lastname: "Larochelle",
    email: "Claresta.Larochelle@yopmail.com",
    email2: "Claresta.Larochelle@gmail.com",
    profession: "worker",
  },
  {
    id: 50,
    firstname: "Rani",
    lastname: "Olin",
    email: "Rani.Olin@yopmail.com",
    email2: "Rani.Olin@gmail.com",
    profession: "firefighter",
  },
  {
    id: 51,
    firstname: "Dulcinea",
    lastname: "Erskine",
    email: "Dulcinea.Erskine@yopmail.com",
    email2: "Dulcinea.Erskine@gmail.com",
    profession: "worker",
  },
  {
    id: 52,
    firstname: "Doro",
    lastname: "Camden",
    email: "Doro.Camden@yopmail.com",
    email2: "Doro.Camden@gmail.com",
    profession: "firefighter",
  },
  {
    id: 53,
    firstname: "Winny",
    lastname: "Engdahl",
    email: "Winny.Engdahl@yopmail.com",
    email2: "Winny.Engdahl@gmail.com",
    profession: "firefighter",
  },
  {
    id: 54,
    firstname: "Linet",
    lastname: "Modie",
    email: "Linet.Modie@yopmail.com",
    email2: "Linet.Modie@gmail.com",
    profession: "police officer",
  },
  {
    id: 55,
    firstname: "Tatiania",
    lastname: "Peti",
    email: "Tatiania.Peti@yopmail.com",
    email2: "Tatiania.Peti@gmail.com",
    profession: "doctor",
  },
  {
    id: 56,
    firstname: "Daune",
    lastname: "Elephus",
    email: "Daune.Elephus@yopmail.com",
    email2: "Daune.Elephus@gmail.com",
    profession: "police officer",
  },
  {
    id: 57,
    firstname: "Olwen",
    lastname: "Seagraves",
    email: "Olwen.Seagraves@yopmail.com",
    email2: "Olwen.Seagraves@gmail.com",
    profession: "police officer",
  },
  {
    id: 58,
    firstname: "Binny",
    lastname: "Merna",
    email: "Binny.Merna@yopmail.com",
    email2: "Binny.Merna@gmail.com",
    profession: "police officer",
  },
  {
    id: 59,
    firstname: "Darlleen",
    lastname: "Hubert",
    email: "Darlleen.Hubert@yopmail.com",
    email2: "Darlleen.Hubert@gmail.com",
    profession: "doctor",
  },
  {
    id: 60,
    firstname: "June",
    lastname: "Bouchard",
    email: "June.Bouchard@yopmail.com",
    email2: "June.Bouchard@gmail.com",
    profession: "firefighter",
  },
  {
    id: 61,
    firstname: "Karly",
    lastname: "Turne",
    email: "Karly.Turne@yopmail.com",
    email2: "Karly.Turne@gmail.com",
    profession: "doctor",
  },
  {
    id: 62,
    firstname: "Lynde",
    lastname: "Eldrid",
    email: "Lynde.Eldrid@yopmail.com",
    email2: "Lynde.Eldrid@gmail.com",
    profession: "developer",
  },
  {
    id: 63,
    firstname: "Deloria",
    lastname: "Ardeha",
    email: "Deloria.Ardeha@yopmail.com",
    email2: "Deloria.Ardeha@gmail.com",
    profession: "police officer",
  },
  {
    id: 64,
    firstname: "Cassandra",
    lastname: "Fabiola",
    email: "Cassandra.Fabiola@yopmail.com",
    email2: "Cassandra.Fabiola@gmail.com",
    profession: "doctor",
  },
  {
    id: 65,
    firstname: "Blake",
    lastname: "Edee",
    email: "Blake.Edee@yopmail.com",
    email2: "Blake.Edee@gmail.com",
    profession: "worker",
  },
  {
    id: 66,
    firstname: "Julieta",
    lastname: "Decato",
    email: "Julieta.Decato@yopmail.com",
    email2: "Julieta.Decato@gmail.com",
    profession: "developer",
  },
  {
    id: 67,
    firstname: "Yolane",
    lastname: "Lubin",
    email: "Yolane.Lubin@yopmail.com",
    email2: "Yolane.Lubin@gmail.com",
    profession: "developer",
  },
  {
    id: 68,
    firstname: "Averyl",
    lastname: "Duwalt",
    email: "Averyl.Duwalt@yopmail.com",
    email2: "Averyl.Duwalt@gmail.com",
    profession: "firefighter",
  },
  {
    id: 69,
    firstname: "Meriel",
    lastname: "Ovid",
    email: "Meriel.Ovid@yopmail.com",
    email2: "Meriel.Ovid@gmail.com",
    profession: "doctor",
  },
  {
    id: 70,
    firstname: "Cacilie",
    lastname: "Jotham",
    email: "Cacilie.Jotham@yopmail.com",
    email2: "Cacilie.Jotham@gmail.com",
    profession: "developer",
  },
  {
    id: 71,
    firstname: "Lorne",
    lastname: "Schalles",
    email: "Lorne.Schalles@yopmail.com",
    email2: "Lorne.Schalles@gmail.com",
    profession: "developer",
  },
  {
    id: 72,
    firstname: "Adriana",
    lastname: "Suzetta",
    email: "Adriana.Suzetta@yopmail.com",
    email2: "Adriana.Suzetta@gmail.com",
    profession: "worker",
  },
  {
    id: 73,
    firstname: "Annabela",
    lastname: "Ogren",
    email: "Annabela.Ogren@yopmail.com",
    email2: "Annabela.Ogren@gmail.com",
    profession: "doctor",
  },
  {
    id: 74,
    firstname: "Lulita",
    lastname: "Voletta",
    email: "Lulita.Voletta@yopmail.com",
    email2: "Lulita.Voletta@gmail.com",
    profession: "worker",
  },
  {
    id: 75,
    firstname: "Rosaline",
    lastname: "Nerita",
    email: "Rosaline.Nerita@yopmail.com",
    email2: "Rosaline.Nerita@gmail.com",
    profession: "police officer",
  },
  {
    id: 76,
    firstname: "Minne",
    lastname: "Florina",
    email: "Minne.Florina@yopmail.com",
    email2: "Minne.Florina@gmail.com",
    profession: "firefighter",
  },
  {
    id: 77,
    firstname: "Genovera",
    lastname: "Warthman",
    email: "Genovera.Warthman@yopmail.com",
    email2: "Genovera.Warthman@gmail.com",
    profession: "firefighter",
  },
  {
    id: 78,
    firstname: "Sonni",
    lastname: "Eachern",
    email: "Sonni.Eachern@yopmail.com",
    email2: "Sonni.Eachern@gmail.com",
    profession: "firefighter",
  },
  {
    id: 79,
    firstname: "Kassey",
    lastname: "Daniele",
    email: "Kassey.Daniele@yopmail.com",
    email2: "Kassey.Daniele@gmail.com",
    profession: "worker",
  },
  {
    id: 80,
    firstname: "Annabela",
    lastname: "Felizio",
    email: "Annabela.Felizio@yopmail.com",
    email2: "Annabela.Felizio@gmail.com",
    profession: "firefighter",
  },
  {
    id: 81,
    firstname: "Ingrid",
    lastname: "Weinreb",
    email: "Ingrid.Weinreb@yopmail.com",
    email2: "Ingrid.Weinreb@gmail.com",
    profession: "firefighter",
  },
  {
    id: 82,
    firstname: "Fawne",
    lastname: "Dreda",
    email: "Fawne.Dreda@yopmail.com",
    email2: "Fawne.Dreda@gmail.com",
    profession: "worker",
  },
  {
    id: 83,
    firstname: "Vonny",
    lastname: "Ezar",
    email: "Vonny.Ezar@yopmail.com",
    email2: "Vonny.Ezar@gmail.com",
    profession: "firefighter",
  },
  {
    id: 84,
    firstname: "Janenna",
    lastname: "Pattin",
    email: "Janenna.Pattin@yopmail.com",
    email2: "Janenna.Pattin@gmail.com",
    profession: "police officer",
  },
  {
    id: 85,
    firstname: "Modestia",
    lastname: "Truc",
    email: "Modestia.Truc@yopmail.com",
    email2: "Modestia.Truc@gmail.com",
    profession: "firefighter",
  },
  {
    id: 86,
    firstname: "Brandise",
    lastname: "Oster",
    email: "Brandise.Oster@yopmail.com",
    email2: "Brandise.Oster@gmail.com",
    profession: "worker",
  },
  {
    id: 87,
    firstname: "Averyl",
    lastname: "Daniele",
    email: "Averyl.Daniele@yopmail.com",
    email2: "Averyl.Daniele@gmail.com",
    profession: "developer",
  },
  {
    id: 88,
    firstname: "Tamqrah",
    lastname: "Hedve",
    email: "Tamqrah.Hedve@yopmail.com",
    email2: "Tamqrah.Hedve@gmail.com",
    profession: "police officer",
  },
  {
    id: 89,
    firstname: "Brana",
    lastname: "Sharl",
    email: "Brana.Sharl@yopmail.com",
    email2: "Brana.Sharl@gmail.com",
    profession: "doctor",
  },
  {
    id: 90,
    firstname: "Lorenza",
    lastname: "Lory",
    email: "Lorenza.Lory@yopmail.com",
    email2: "Lorenza.Lory@gmail.com",
    profession: "doctor",
  },
  {
    id: 91,
    firstname: "Jennica",
    lastname: "Tybald",
    email: "Jennica.Tybald@yopmail.com",
    email2: "Jennica.Tybald@gmail.com",
    profession: "worker",
  },
  {
    id: 92,
    firstname: "Desirae",
    lastname: "Pacorro",
    email: "Desirae.Pacorro@yopmail.com",
    email2: "Desirae.Pacorro@gmail.com",
    profession: "police officer",
  },
  {
    id: 93,
    firstname: "Deedee",
    lastname: "Zitvaa",
    email: "Deedee.Zitvaa@yopmail.com",
    email2: "Deedee.Zitvaa@gmail.com",
    profession: "worker",
  },
  {
    id: 94,
    firstname: "Tori",
    lastname: "Allare",
    email: "Tori.Allare@yopmail.com",
    email2: "Tori.Allare@gmail.com",
    profession: "developer",
  },
  {
    id: 95,
    firstname: "Aimil",
    lastname: "Schroth",
    email: "Aimil.Schroth@yopmail.com",
    email2: "Aimil.Schroth@gmail.com",
    profession: "worker",
  },
  {
    id: 96,
    firstname: "Blinni",
    lastname: "Creamer",
    email: "Blinni.Creamer@yopmail.com",
    email2: "Blinni.Creamer@gmail.com",
    profession: "doctor",
  },
  {
    id: 97,
    firstname: "Jackie",
    lastname: "Ledah",
    email: "Jackie.Ledah@yopmail.com",
    email2: "Jackie.Ledah@gmail.com",
    profession: "doctor",
  },
  {
    id: 98,
    firstname: "Genevra",
    lastname: "Peg",
    email: "Genevra.Peg@yopmail.com",
    email2: "Genevra.Peg@gmail.com",
    profession: "developer",
  },
  {
    id: 99,
    firstname: "Kirstin",
    lastname: "Lytton",
    email: "Kirstin.Lytton@yopmail.com",
    email2: "Kirstin.Lytton@gmail.com",
    profession: "developer",
  },
  {
    id: 100,
    firstname: "Jemie",
    lastname: "Francene",
    email: "Jemie.Francene@yopmail.com",
    email2: "Jemie.Francene@gmail.com",
    profession: "worker",
  },
];

const musicGenreJSONData = [
  {
    instance_id: 32894,
    artist_name: "Röyksopp",
    track_name: "Röyksopp's Night Out",
    popularity: 27,
    acousticness: 0.00468,
    danceability: 0.652,
    duration_ms: -1,
    energy: 0.941,
    instrumentalness: 0.792,
    key: "A#",
    liveness: 0.115,
    loudness: -5.2010000000000005,
    mode: "Minor",
    speechiness: 0.0748,
    tempo: 100.889,
    obtained_date: "4-Apr",
    valence: 0.759,
    music_genre: "Electronic",
  },
  {
    instance_id: 46652,
    artist_name: "Thievery Corporation",
    track_name: "The Shining Path",
    popularity: 31,
    acousticness: 0.0127,
    danceability: 0.622,
    duration_ms: 218293,
    energy: 0.89,
    instrumentalness: 0.95,
    key: "D",
    liveness: 0.124,
    loudness: -7.042999999999999,
    mode: "Minor",
    speechiness: 0.03,
    tempo: 115.00200000000001,
    obtained_date: "4-Apr",
    valence: 0.531,
    music_genre: "Electronic",
  },
  {
    instance_id: 30097,
    artist_name: "Dillon Francis",
    track_name: "Hurricane",
    popularity: 28,
    acousticness: 0.00306,
    danceability: 0.62,
    duration_ms: 215613,
    energy: 0.755,
    instrumentalness: 0.0118,
    key: "G#",
    liveness: 0.534,
    loudness: -4.617,
    mode: "Major",
    speechiness: 0.0345,
    tempo: 127.994,
    obtained_date: "4-Apr",
    valence: 0.3329999999999999,
    music_genre: "Electronic",
  },
  {
    instance_id: 62177,
    artist_name: "Dubloadz",
    track_name: "Nitro",
    popularity: 34,
    acousticness: 0.0254,
    danceability: 0.774,
    duration_ms: 166875,
    energy: 0.7,
    instrumentalness: 0.00253,
    key: "C#",
    liveness: 0.157,
    loudness: -4.498,
    mode: "Major",
    speechiness: 0.239,
    tempo: 128.014,
    obtained_date: "4-Apr",
    valence: 0.27,
    music_genre: "Electronic",
  },
  {
    instance_id: 24907,
    artist_name: "What So Not",
    track_name: "Divide & Conquer",
    popularity: 32,
    acousticness: 0.00465,
    danceability: 0.638,
    duration_ms: 222369,
    energy: 0.5870000000000001,
    instrumentalness: 0.909,
    key: "F#",
    liveness: 0.157,
    loudness: -6.266,
    mode: "Major",
    speechiness: 0.0413,
    tempo: 145.036,
    obtained_date: "4-Apr",
    valence: 0.3229999999999999,
    music_genre: "Electronic",
  },
  {
    instance_id: 89064,
    artist_name: "Axel Boman",
    track_name: "Hello",
    popularity: 47,
    acousticness: 0.0052299999999999,
    danceability: 0.755,
    duration_ms: 519468,
    energy: 0.731,
    instrumentalness: 0.8540000000000001,
    key: "D",
    liveness: 0.216,
    loudness: -10.517,
    mode: "Minor",
    speechiness: 0.0412,
    tempo: "?",
    obtained_date: "4-Apr",
    valence: 0.614,
    music_genre: "Electronic",
  },
  {
    instance_id: 43760,
    artist_name: "Jordan Comolli",
    track_name: "Clash",
    popularity: 46,
    acousticness: 0.0289,
    danceability: 0.5720000000000001,
    duration_ms: 214408,
    energy: 0.8029999999999999,
    instrumentalness: 0.00000774,
    key: "B",
    liveness: 0.106,
    loudness: -4.294,
    mode: "Major",
    speechiness: 0.351,
    tempo: 149.995,
    obtained_date: "4-Apr",
    valence: 0.23,
    music_genre: "Electronic",
  },
  {
    instance_id: 30738,
    artist_name: "Hraach",
    track_name: "Delirio",
    popularity: 43,
    acousticness: 0.0297,
    danceability: 0.809,
    duration_ms: 416132,
    energy: 0.706,
    instrumentalness: 0.903,
    key: "G",
    liveness: 0.0635,
    loudness: -9.339,
    mode: "Minor",
    speechiness: 0.0484,
    tempo: 120.008,
    obtained_date: "4-Apr",
    valence: 0.7609999999999999,
    music_genre: "Electronic",
  },
  {
    instance_id: 84950,
    artist_name: "Kayzo",
    track_name: "NEVER ALONE",
    popularity: 39,
    acousticness: 0.00299,
    danceability: 0.509,
    duration_ms: 292800,
    energy: 0.921,
    instrumentalness: 0.000276,
    key: "F",
    liveness: 0.178,
    loudness: -3.175,
    mode: "Minor",
    speechiness: 0.268,
    tempo: 149.94799999999998,
    obtained_date: "4-Apr",
    valence: 0.273,
    music_genre: "Electronic",
  },
  {
    instance_id: 56950,
    artist_name: "Shlump",
    track_name: "Lazer Beam",
    popularity: 22,
    acousticness: 0.00934,
    danceability: 0.578,
    duration_ms: 204800,
    energy: 0.731,
    instrumentalness: 0.0112,
    key: "A",
    liveness: 0.111,
    loudness: -7.091,
    mode: "Minor",
    speechiness: 0.173,
    tempo: 139.933,
    obtained_date: "4-Apr",
    valence: 0.203,
    music_genre: "Electronic",
  },
  {
    instance_id: 49030,
    artist_name: "Chase & Status",
    track_name: "Lost & Not Found - Acoustic",
    popularity: 30,
    acousticness: 0.855,
    danceability: 0.607,
    duration_ms: 170463,
    energy: 0.158,
    instrumentalness: 0,
    key: "F#",
    liveness: 0.106,
    loudness: -13.787,
    mode: "Minor",
    speechiness: 0.0345,
    tempo: 57.528,
    obtained_date: "4-Apr",
    valence: 0.307,
    music_genre: "Electronic",
  },
  {
    instance_id: 22654,
    artist_name: "G Jones",
    track_name: "Mind",
    popularity: 27,
    acousticness: 0.0337,
    danceability: 0.513,
    duration_ms: 165132,
    energy: 0.828,
    instrumentalness: 0.569,
    key: "B",
    liveness: 0.109,
    loudness: -5.439,
    mode: "Minor",
    speechiness: 0.0609,
    tempo: 178.543,
    obtained_date: "3-Apr",
    valence: 0.0591,
    music_genre: "Electronic",
  },
  {
    instance_id: 69056,
    artist_name: "Champagne Drip",
    track_name: "Satellite (Feat. Len X)",
    popularity: 31,
    acousticness: 0.016,
    danceability: 0.66,
    duration_ms: 236089,
    energy: 0.892,
    instrumentalness: 0.000605,
    key: "C",
    liveness: 0.163,
    loudness: -3.464,
    mode: "Major",
    speechiness: 0.0645,
    tempo: 128.043,
    obtained_date: "4-Apr",
    valence: 0.111,
    music_genre: "Electronic",
  },
  {
    instance_id: 62039,
    artist_name: "DJ Shadow",
    track_name: "Broken Levee Blues",
    popularity: 31,
    acousticness: 0.86,
    danceability: 0.737,
    duration_ms: -1,
    energy: 0.405,
    instrumentalness: 0.0361,
    key: "A",
    liveness: 0.173,
    loudness: -10.536,
    mode: "Minor",
    speechiness: 0.0424,
    tempo: 154.745,
    obtained_date: "4-Apr",
    valence: 0.647,
    music_genre: "Electronic",
  },
  {
    instance_id: 49205,
    artist_name: "Getter",
    track_name: "Bonesaw",
    popularity: 27,
    acousticness: 0.000194,
    danceability: 0.601,
    duration_ms: 243857,
    energy: 0.969,
    instrumentalness: 0.7759999999999999,
    key: "D",
    liveness: 0.409,
    loudness: -1.5530000000000002,
    mode: "Major",
    speechiness: 0.185,
    tempo: 139.911,
    obtained_date: "4-Apr",
    valence: 0.198,
    music_genre: "Electronic",
  },
  {
    instance_id: 83192,
    artist_name: "Excision",
    track_name: "Bring the Madness (Noisestorm Remix) [feat. Mayor Apeshit]",
    popularity: 50,
    acousticness: 0.00331,
    danceability: 0.391,
    duration_ms: 240000,
    energy: 0.957,
    instrumentalness: 0.22,
    key: "G",
    liveness: 0.1119999999999999,
    loudness: -2.51,
    mode: "Major",
    speechiness: 0.0904,
    tempo: 100.024,
    obtained_date: "4-Apr",
    valence: 0.121,
    music_genre: "Electronic",
  },
  {
    instance_id: 83926,
    artist_name: "San Holo",
    track_name: "One Thing",
    popularity: 59,
    acousticness: 0.136,
    danceability: 0.336,
    duration_ms: -1,
    energy: 0.746,
    instrumentalness: 0,
    key: "C#",
    liveness: 0.737,
    loudness: -4.315,
    mode: "Minor",
    speechiness: 0.0685,
    tempo: 151.756,
    obtained_date: "4-Apr",
    valence: 0.21,
    music_genre: "Electronic",
  },
  {
    instance_id: 54696,
    artist_name: "Dillon Francis",
    track_name: "Without You - The Rebirth",
    popularity: 29,
    acousticness: 0.158,
    danceability: 0.66,
    duration_ms: 266282,
    energy: 0.784,
    instrumentalness: 0.000279,
    key: "C",
    liveness: 0.0978,
    loudness: -4.396,
    mode: "Minor",
    speechiness: 0.0571,
    tempo: 127.958,
    obtained_date: "3-Apr",
    valence: 0.622,
    music_genre: "Electronic",
  },
  {
    instance_id: 49375,
    artist_name: "The Bloody Beetroots",
    track_name: "Irreversible (feat. Anders Friden)",
    popularity: 35,
    acousticness: 0.0000602,
    danceability: 0.259,
    duration_ms: 185333,
    energy: 0.687,
    instrumentalness: 0.00862,
    key: "G#",
    liveness: 0.3379999999999999,
    loudness: -3.2310000000000003,
    mode: "Major",
    speechiness: 0.0413,
    tempo: 135.532,
    obtained_date: "4-Apr",
    valence: 0.114,
    music_genre: "Electronic",
  },
];

const CSVString = `id,firstname,lastname,email,email2,profession
1,Rosanne,Fancie,Rosanne.Fancie@yopmail.com,Rosanne.Fancie@gmail.com,firefighter
2,Elsie,Mathilde,Elsie.Mathilde@yopmail.com,Elsie.Mathilde@gmail.com,firefighter
3,Britni,Si,Britni.Si@yopmail.com,Britni.Si@gmail.com,police officer
4,Brynna,Warthman,Brynna.Warthman@yopmail.com,Brynna.Warthman@gmail.com,worker
5,Nessie,Septima,Nessie.Septima@yopmail.com,Nessie.Septima@gmail.com,doctor
6,Tina,Rona,Tina.Rona@yopmail.com,Tina.Rona@gmail.com,developer
7,Dania,Thad,Dania.Thad@yopmail.com,Dania.Thad@gmail.com,firefighter
8,Genevra,Susannah,Genevra.Susannah@yopmail.com,Genevra.Susannah@gmail.com,police officer
9,Ivett,Alexandr,Ivett.Alexandr@yopmail.com,Ivett.Alexandr@gmail.com,police officer
10,Mady,Chrystel,Mady.Chrystel@yopmail.com,Mady.Chrystel@gmail.com,doctor
11,Belinda,Anderea,Belinda.Anderea@yopmail.com,Belinda.Anderea@gmail.com,worker
12,Kristan,Gavrila,Kristan.Gavrila@yopmail.com,Kristan.Gavrila@gmail.com,firefighter
13,Antonietta,Nance,Antonietta.Nance@yopmail.com,Antonietta.Nance@gmail.com,doctor
14,Carmela,Jefferey,Carmela.Jefferey@yopmail.com,Carmela.Jefferey@gmail.com,developer
15,Ebonee,Shields,Ebonee.Shields@yopmail.com,Ebonee.Shields@gmail.com,firefighter
16,Allis,Norvol,Allis.Norvol@yopmail.com,Allis.Norvol@gmail.com,police officer
17,Mireielle,Ahab,Mireielle.Ahab@yopmail.com,Mireielle.Ahab@gmail.com,doctor
18,Tracey,Laverne,Tracey.Laverne@yopmail.com,Tracey.Laverne@gmail.com,doctor
19,Robinia,Autrey,Robinia.Autrey@yopmail.com,Robinia.Autrey@gmail.com,police officer
20,Imojean,Alarise,Imojean.Alarise@yopmail.com,Imojean.Alarise@gmail.com,police officer
21,Basia,Leler,Basia.Leler@yopmail.com,Basia.Leler@gmail.com,developer
22,Maryellen,Kylander,Maryellen.Kylander@yopmail.com,Maryellen.Kylander@gmail.com,police officer
23,Rivalee,Heidt,Rivalee.Heidt@yopmail.com,Rivalee.Heidt@gmail.com,firefighter
24,Barbi,Shanley,Barbi.Shanley@yopmail.com,Barbi.Shanley@gmail.com,doctor
25,Lilith,Old,Lilith.Old@yopmail.com,Lilith.Old@gmail.com,developer
26,Caressa,Rolf,Caressa.Rolf@yopmail.com,Caressa.Rolf@gmail.com,developer
27,Misha,Toni,Misha.Toni@yopmail.com,Misha.Toni@gmail.com,doctor
28,Elena,Douglass,Elena.Douglass@yopmail.com,Elena.Douglass@gmail.com,firefighter
29,Liana,Kiersten,Liana.Kiersten@yopmail.com,Liana.Kiersten@gmail.com,police officer
30,Tera,Dalli,Tera.Dalli@yopmail.com,Tera.Dalli@gmail.com,police officer
31,Catrina,Behre,Catrina.Behre@yopmail.com,Catrina.Behre@gmail.com,police officer
32,Carmela,Douglass,Carmela.Douglass@yopmail.com,Carmela.Douglass@gmail.com,worker
33,Kathy,Sidonius,Kathy.Sidonius@yopmail.com,Kathy.Sidonius@gmail.com,worker
34,Nerta,Monk,Nerta.Monk@yopmail.com,Nerta.Monk@gmail.com,doctor
35,Shirlee,Mata,Shirlee.Mata@yopmail.com,Shirlee.Mata@gmail.com,police officer
36,Joane,Tybald,Joane.Tybald@yopmail.com,Joane.Tybald@gmail.com,police officer
37,Flo,Sheedy,Flo.Sheedy@yopmail.com,Flo.Sheedy@gmail.com,doctor
38,Concettina,Libna,Concettina.Libna@yopmail.com,Concettina.Libna@gmail.com,firefighter
39,Petronia,Middleton,Petronia.Middleton@yopmail.com,Petronia.Middleton@gmail.com,firefighter
40,Sissy,Sammons,Sissy.Sammons@yopmail.com,Sissy.Sammons@gmail.com,police officer
41,Paulita,Isidore,Paulita.Isidore@yopmail.com,Paulita.Isidore@gmail.com,worker
42,Deedee,Raychel,Deedee.Raychel@yopmail.com,Deedee.Raychel@gmail.com,worker
43,Cathyleen,Ivens,Cathyleen.Ivens@yopmail.com,Cathyleen.Ivens@gmail.com,developer
44,Kaia,Adlare,Kaia.Adlare@yopmail.com,Kaia.Adlare@gmail.com,worker
45,Romona,Rossner,Romona.Rossner@yopmail.com,Romona.Rossner@gmail.com,worker
46,Fanny,Faro,Fanny.Faro@yopmail.com,Fanny.Faro@gmail.com,worker
47,Genovera,Hamil,Genovera.Hamil@yopmail.com,Genovera.Hamil@gmail.com,developer
48,Randa,Maribeth,Randa.Maribeth@yopmail.com,Randa.Maribeth@gmail.com,worker
49,Claresta,Larochelle,Claresta.Larochelle@yopmail.com,Claresta.Larochelle@gmail.com,worker
50,Rani,Olin,Rani.Olin@yopmail.com,Rani.Olin@gmail.com,firefighter
51,Dulcinea,Erskine,Dulcinea.Erskine@yopmail.com,Dulcinea.Erskine@gmail.com,worker
52,Doro,Camden,Doro.Camden@yopmail.com,Doro.Camden@gmail.com,firefighter
53,Winny,Engdahl,Winny.Engdahl@yopmail.com,Winny.Engdahl@gmail.com,firefighter
54,Linet,Modie,Linet.Modie@yopmail.com,Linet.Modie@gmail.com,police officer
55,Tatiania,Peti,Tatiania.Peti@yopmail.com,Tatiania.Peti@gmail.com,doctor
56,Daune,Elephus,Daune.Elephus@yopmail.com,Daune.Elephus@gmail.com,police officer
57,Olwen,Seagraves,Olwen.Seagraves@yopmail.com,Olwen.Seagraves@gmail.com,police officer
58,Binny,Merna,Binny.Merna@yopmail.com,Binny.Merna@gmail.com,police officer
59,Darlleen,Hubert,Darlleen.Hubert@yopmail.com,Darlleen.Hubert@gmail.com,doctor
60,June,Bouchard,June.Bouchard@yopmail.com,June.Bouchard@gmail.com,firefighter
61,Karly,Turne,Karly.Turne@yopmail.com,Karly.Turne@gmail.com,doctor
62,Lynde,Eldrid,Lynde.Eldrid@yopmail.com,Lynde.Eldrid@gmail.com,developer
63,Deloria,Ardeha,Deloria.Ardeha@yopmail.com,Deloria.Ardeha@gmail.com,police officer
64,Cassandra,Fabiola,Cassandra.Fabiola@yopmail.com,Cassandra.Fabiola@gmail.com,doctor
65,Blake,Edee,Blake.Edee@yopmail.com,Blake.Edee@gmail.com,worker
66,Julieta,Decato,Julieta.Decato@yopmail.com,Julieta.Decato@gmail.com,developer
67,Yolane,Lubin,Yolane.Lubin@yopmail.com,Yolane.Lubin@gmail.com,developer
68,Averyl,Duwalt,Averyl.Duwalt@yopmail.com,Averyl.Duwalt@gmail.com,firefighter
69,Meriel,Ovid,Meriel.Ovid@yopmail.com,Meriel.Ovid@gmail.com,doctor
70,Cacilie,Jotham,Cacilie.Jotham@yopmail.com,Cacilie.Jotham@gmail.com,developer
71,Lorne,Schalles,Lorne.Schalles@yopmail.com,Lorne.Schalles@gmail.com,developer
72,Adriana,Suzetta,Adriana.Suzetta@yopmail.com,Adriana.Suzetta@gmail.com,worker
73,Annabela,Ogren,Annabela.Ogren@yopmail.com,Annabela.Ogren@gmail.com,doctor
74,Lulita,Voletta,Lulita.Voletta@yopmail.com,Lulita.Voletta@gmail.com,worker
75,Rosaline,Nerita,Rosaline.Nerita@yopmail.com,Rosaline.Nerita@gmail.com,police officer
76,Minne,Florina,Minne.Florina@yopmail.com,Minne.Florina@gmail.com,firefighter
77,Genovera,Warthman,Genovera.Warthman@yopmail.com,Genovera.Warthman@gmail.com,firefighter
78,Sonni,Eachern,Sonni.Eachern@yopmail.com,Sonni.Eachern@gmail.com,firefighter
79,Kassey,Daniele,Kassey.Daniele@yopmail.com,Kassey.Daniele@gmail.com,worker
80,Annabela,Felizio,Annabela.Felizio@yopmail.com,Annabela.Felizio@gmail.com,firefighter
81,Ingrid,Weinreb,Ingrid.Weinreb@yopmail.com,Ingrid.Weinreb@gmail.com,firefighter
82,Fawne,Dreda,Fawne.Dreda@yopmail.com,Fawne.Dreda@gmail.com,worker
83,Vonny,Ezar,Vonny.Ezar@yopmail.com,Vonny.Ezar@gmail.com,firefighter
84,Janenna,Pattin,Janenna.Pattin@yopmail.com,Janenna.Pattin@gmail.com,police officer
85,Modestia,Truc,Modestia.Truc@yopmail.com,Modestia.Truc@gmail.com,firefighter
86,Brandise,Oster,Brandise.Oster@yopmail.com,Brandise.Oster@gmail.com,worker
87,Averyl,Daniele,Averyl.Daniele@yopmail.com,Averyl.Daniele@gmail.com,developer
88,Tamqrah,Hedve,Tamqrah.Hedve@yopmail.com,Tamqrah.Hedve@gmail.com,police officer
89,Brana,Sharl,Brana.Sharl@yopmail.com,Brana.Sharl@gmail.com,doctor
90,Lorenza,Lory,Lorenza.Lory@yopmail.com,Lorenza.Lory@gmail.com,doctor
91,Jennica,Tybald,Jennica.Tybald@yopmail.com,Jennica.Tybald@gmail.com,worker
92,Desirae,Pacorro,Desirae.Pacorro@yopmail.com,Desirae.Pacorro@gmail.com,police officer
93,Deedee,Zitvaa,Deedee.Zitvaa@yopmail.com,Deedee.Zitvaa@gmail.com,worker
94,Tori,Allare,Tori.Allare@yopmail.com,Tori.Allare@gmail.com,developer
95,Aimil,Schroth,Aimil.Schroth@yopmail.com,Aimil.Schroth@gmail.com,worker
96,Blinni,Creamer,Blinni.Creamer@yopmail.com,Blinni.Creamer@gmail.com,doctor
97,Jackie,Ledah,Jackie.Ledah@yopmail.com,Jackie.Ledah@gmail.com,doctor
98,Genevra,Peg,Genevra.Peg@yopmail.com,Genevra.Peg@gmail.com,developer
99,Kirstin,Lytton,Kirstin.Lytton@yopmail.com,Kirstin.Lytton@gmail.com,developer
100,Jemie,Francene,Jemie.Francene@yopmail.com,Jemie.Francene@gmail.com,worker`;

const singleLineString = `id,firstname,lastname,email,email2,profession\n 1,Rosanne,Fancie,Rosanne.Fancie@yopmail.com,Rosanne.Fancie@gmail.com,firefighter\n 2,Elsie,Mathilde,Elsie.Mathilde@yopmail.com,Elsie.Mathilde@gmail.com,firefighter\n 3,Britni,Si,Britni.Si@yopmail.com,Britni.Si@gmail.com,police officer\n 4,Brynna,Warthman,Brynna.Warthman@yopmail.com,Brynna.Warthman@gmail.com,worker\n 5,Nessie,Septima,Nessie.Septima@yopmail.com,Nessie.Septima@gmail.com,doctor\n 6,Tina,Rona,Tina.Rona@yopmail.com,Tina.Rona@gmail.com,developer\n 7,Dania,Thad,Dania.Thad@yopmail.com,Dania.Thad@gmail.com,firefighter\n 8,Genevra,Susannah,Genevra.Susannah@yopmail.com,Genevra.Susannah@gmail.com,police officer\n 9,Ivett,Alexandr,Ivett.Alexandr@yopmail.com,Ivett.Alexandr@gmail.com,police officer\n 10,Mady,Chrystel,Mady.Chrystel@yopmail.com,Mady.Chrystel@gmail.com,doctor\n 11,Belinda,Anderea,Belinda.Anderea@yopmail.com,Belinda.Anderea@gmail.com,worker\n 12,Kristan,Gavrila,Kristan.Gavrila@yopmail.com,Kristan.Gavrila@gmail.com,firefighter\n 13,Antonietta,Nance,Antonietta.Nance@yopmail.com,Antonietta.Nance@gmail.com,doctor\n 14,Carmela,Jefferey,Carmela.Jefferey@yopmail.com,Carmela.Jefferey@gmail.com,developer\n 15,Ebonee,Shields,Ebonee.Shields@yopmail.com,Ebonee.Shields@gmail.com,firefighter\n 16,Allis,Norvol,Allis.Norvol@yopmail.com,Allis.Norvol@gmail.com,police officer\n 17,Mireielle,Ahab,Mireielle.Ahab@yopmail.com,Mireielle.Ahab@gmail.com,doctor\n 18,Tracey,Laverne,Tracey.Laverne@yopmail.com,Tracey.Laverne@gmail.com,doctor\n 19,Robinia,Autrey,Robinia.Autrey@yopmail.com,Robinia.Autrey@gmail.com,police officer\n 20,Imojean,Alarise,Imojean.Alarise@yopmail.com,Imojean.Alarise@gmail.com,police officer\n 21,Basia,Leler,Basia.Leler@yopmail.com,Basia.Leler@gmail.com,developer\n 22,Maryellen,Kylander,Maryellen.Kylander@yopmail.com,Maryellen.Kylander@gmail.com,police officer\n 23,Rivalee,Heidt,Rivalee.Heidt@yopmail.com,Rivalee.Heidt@gmail.com,firefighter\n 24,Barbi,Shanley,Barbi.Shanley@yopmail.com,Barbi.Shanley@gmail.com,doctor\n 25,Lilith,Old,Lilith.Old@yopmail.com,Lilith.Old@gmail.com,developer\n 26,Caressa,Rolf,Caressa.Rolf@yopmail.com,Caressa.Rolf@gmail.com,developer\n 27,Misha,Toni,Misha.Toni@yopmail.com,Misha.Toni@gmail.com,doctor\n 28,Elena,Douglass,Elena.Douglass@yopmail.com,Elena.Douglass@gmail.com,firefighter\n 29,Liana,Kiersten,Liana.Kiersten@yopmail.com,Liana.Kiersten@gmail.com,police officer\n 30,Tera,Dalli,Tera.Dalli@yopmail.com,Tera.Dalli@gmail.com,police officer\n 31,Catrina,Behre,Catrina.Behre@yopmail.com,Catrina.Behre@gmail.com,police officer\n 32,Carmela,Douglass,Carmela.Douglass@yopmail.com,Carmela.Douglass@gmail.com,worker\n 33,Kathy,Sidonius,Kathy.Sidonius@yopmail.com,Kathy.Sidonius@gmail.com,worker\n 34,Nerta,Monk,Nerta.Monk@yopmail.com,Nerta.Monk@gmail.com,doctor\n 35,Shirlee,Mata,Shirlee.Mata@yopmail.com,Shirlee.Mata@gmail.com,police officer\n 36,Joane,Tybald,Joane.Tybald@yopmail.com,Joane.Tybald@gmail.com,police officer\n 37,Flo,Sheedy,Flo.Sheedy@yopmail.com,Flo.Sheedy@gmail.com,doctor\n 38,Concettina,Libna,Concettina.Libna@yopmail.com,Concettina.Libna@gmail.com,firefighter\n 39,Petronia,Middleton,Petronia.Middleton@yopmail.com,Petronia.Middleton@gmail.com,firefighter\n 40,Sissy,Sammons,Sissy.Sammons@yopmail.com,Sissy.Sammons@gmail.com,police officer\n 41,Paulita,Isidore,Paulita.Isidore@yopmail.com,Paulita.Isidore@gmail.com,worker\n 42,Deedee,Raychel,Deedee.Raychel@yopmail.com,Deedee.Raychel@gmail.com,worker\n 43,Cathyleen,Ivens,Cathyleen.Ivens@yopmail.com,Cathyleen.Ivens@gmail.com,developer\n 44,Kaia,Adlare,Kaia.Adlare@yopmail.com,Kaia.Adlare@gmail.com,worker\n 45,Romona,Rossner,Romona.Rossner@yopmail.com,Romona.Rossner@gmail.com,worker\n 46,Fanny,Faro,Fanny.Faro@yopmail.com,Fanny.Faro@gmail.com,worker\n 47,Genovera,Hamil,Genovera.Hamil@yopmail.com,Genovera.Hamil@gmail.com,developer\n 48,Randa,Maribeth,Randa.Maribeth@yopmail.com,Randa.Maribeth@gmail.com,worker\n 49,Claresta,Larochelle,Claresta.Larochelle@yopmail.com,Claresta.Larochelle@gmail.com,worker\n 50,Rani,Olin,Rani.Olin@yopmail.com,Rani.Olin@gmail.com,firefighter\n 51,Dulcinea,Erskine,Dulcinea.Erskine@yopmail.com,Dulcinea.Erskine@gmail.com,worker\n 52,Doro,Camden,Doro.Camden@yopmail.com,Doro.Camden@gmail.com,firefighter\n 53,Winny,Engdahl,Winny.Engdahl@yopmail.com,Winny.Engdahl@gmail.com,firefighter\n 54,Linet,Modie,Linet.Modie@yopmail.com,Linet.Modie@gmail.com,police officer\n 55,Tatiania,Peti,Tatiania.Peti@yopmail.com,Tatiania.Peti@gmail.com,doctor\n 56,Daune,Elephus,Daune.Elephus@yopmail.com,Daune.Elephus@gmail.com,police officer\n 57,Olwen,Seagraves,Olwen.Seagraves@yopmail.com,Olwen.Seagraves@gmail.com,police officer\n 58,Binny,Merna,Binny.Merna@yopmail.com,Binny.Merna@gmail.com,police officer\n 59,Darlleen,Hubert,Darlleen.Hubert@yopmail.com,Darlleen.Hubert@gmail.com,doctor\n 60,June,Bouchard,June.Bouchard@yopmail.com,June.Bouchard@gmail.com,firefighter\n 61,Karly,Turne,Karly.Turne@yopmail.com,Karly.Turne@gmail.com,doctor\n 62,Lynde,Eldrid,Lynde.Eldrid@yopmail.com,Lynde.Eldrid@gmail.com,developer\n 63,Deloria,Ardeha,Deloria.Ardeha@yopmail.com,Deloria.Ardeha@gmail.com,police officer\n 64,Cassandra,Fabiola,Cassandra.Fabiola@yopmail.com,Cassandra.Fabiola@gmail.com,doctor\n 65,Blake,Edee,Blake.Edee@yopmail.com,Blake.Edee@gmail.com,worker\n 66,Julieta,Decato,Julieta.Decato@yopmail.com,Julieta.Decato@gmail.com,developer\n 67,Yolane,Lubin,Yolane.Lubin@yopmail.com,Yolane.Lubin@gmail.com,developer\n 68,Averyl,Duwalt,Averyl.Duwalt@yopmail.com,Averyl.Duwalt@gmail.com,firefighter\n 69,Meriel,Ovid,Meriel.Ovid@yopmail.com,Meriel.Ovid@gmail.com,doctor\n 70,Cacilie,Jotham,Cacilie.Jotham@yopmail.com,Cacilie.Jotham@gmail.com,developer\n 71,Lorne,Schalles,Lorne.Schalles@yopmail.com,Lorne.Schalles@gmail.com,developer\n 72,Adriana,Suzetta,Adriana.Suzetta@yopmail.com,Adriana.Suzetta@gmail.com,worker\n 73,Annabela,Ogren,Annabela.Ogren@yopmail.com,Annabela.Ogren@gmail.com,doctor\n 74,Lulita,Voletta,Lulita.Voletta@yopmail.com,Lulita.Voletta@gmail.com,worker\n 75,Rosaline,Nerita,Rosaline.Nerita@yopmail.com,Rosaline.Nerita@gmail.com,police officer\n 76,Minne,Florina,Minne.Florina@yopmail.com,Minne.Florina@gmail.com,firefighter\n 77,Genovera,Warthman,Genovera.Warthman@yopmail.com,Genovera.Warthman@gmail.com,firefighter\n 78,Sonni,Eachern,Sonni.Eachern@yopmail.com,Sonni.Eachern@gmail.com,firefighter\n 79,Kassey,Daniele,Kassey.Daniele@yopmail.com,Kassey.Daniele@gmail.com,worker\n 80,Annabela,Felizio,Annabela.Felizio@yopmail.com,Annabela.Felizio@gmail.com,firefighter\n 81,Ingrid,Weinreb,Ingrid.Weinreb@yopmail.com,Ingrid.Weinreb@gmail.com,firefighter\n 82,Fawne,Dreda,Fawne.Dreda@yopmail.com,Fawne.Dreda@gmail.com,worker\n 83,Vonny,Ezar,Vonny.Ezar@yopmail.com,Vonny.Ezar@gmail.com,firefighter\n 84,Janenna,Pattin,Janenna.Pattin@yopmail.com,Janenna.Pattin@gmail.com,police officer\n 85,Modestia,Truc,Modestia.Truc@yopmail.com,Modestia.Truc@gmail.com,firefighter\n 86,Brandise,Oster,Brandise.Oster@yopmail.com,Brandise.Oster@gmail.com,worker\n 87,Averyl,Daniele,Averyl.Daniele@yopmail.com,Averyl.Daniele@gmail.com,developer\n 88,Tamqrah,Hedve,Tamqrah.Hedve@yopmail.com,Tamqrah.Hedve@gmail.com,police officer\n 89,Brana,Sharl,Brana.Sharl@yopmail.com,Brana.Sharl@gmail.com,doctor\n 90,Lorenza,Lory,Lorenza.Lory@yopmail.com,Lorenza.Lory@gmail.com,doctor\n 91,Jennica,Tybald,Jennica.Tybald@yopmail.com,Jennica.Tybald@gmail.com,worker\n 92,Desirae,Pacorro,Desirae.Pacorro@yopmail.com,Desirae.Pacorro@gmail.com,police officer\n 93,Deedee,Zitvaa,Deedee.Zitvaa@yopmail.com,Deedee.Zitvaa@gmail.com,worker\n 94,Tori,Allare,Tori.Allare@yopmail.com,Tori.Allare@gmail.com,developer\n 95,Aimil,Schroth,Aimil.Schroth@yopmail.com,Aimil.Schroth@gmail.com,worker\n 96,Blinni,Creamer,Blinni.Creamer@yopmail.com,Blinni.Creamer@gmail.com,doctor\n 97,Jackie,Ledah,Jackie.Ledah@yopmail.com,Jackie.Ledah@gmail.com,doctor\n 98,Genevra,Peg,Genevra.Peg@yopmail.com,Genevra.Peg@gmail.com,developer\n 99,Kirstin,Lytton,Kirstin.Lytton@yopmail.com,Kirstin.Lytton@gmail.com,developer\n 100,Jemie,Francene,Jemie.Francene@yopmail.com,Jemie.Francene@gmail.com,worker\n`;

const multipleNewLineString = `id,firstname,lastname,email,email2,profession\n 1,Rosanne,Fancie,Rosanne.Fancie@yopmail.com,Rosanne.Fancie@gmail.com,firefighter\n 2,Elsie,Mathilde,Elsie.Mathilde@yopmail.com,Elsie.Mathilde@gmail.com,firefighter\n 3,Britni,Si,Britni.Si@yopmail.com,Britni.Si@gmail.com,police officer\n 4,Brynna,Warthman,Brynna.Warthman@yopmail.com,Brynna.Warthman@gmail.com,worker\n 5,Nessie,Septima,Nessie.Septima@yopmail.com,Nessie.Septima@gmail.com,doctor\n 6,Tina,Rona,Tina.Rona@yopmail.com,Tina.Rona@gmail.com,developer\n 7,Dania,Thad,Dania.Thad@yopmail.com,Dania.Thad@gmail.com,firefighter\n 8,Genevra,Susannah,Genevra.Susannah@yopmail.com,Genevra.Susannah@gmail.com,police officer\n 9,Ivett,Alexandr,Ivett.Alexandr@yopmail.com,Ivett.Alexandr@gmail.com,police officer\n 10,Mady,Chrystel,Mady.Chrystel@yopmail.com,Mady.Chrystel@gmail.com,doctor\n 11,Belinda,Anderea,Belinda.Anderea@yopmail.com,Belinda.Anderea@gmail.com,worker\n 12,Kristan,Gavrila,Kristan.Gavrila@yopmail.com,Kristan.Gavrila@gmail.com,firefighter\n 13,Antonietta,Nance,Antonietta.Nance@yopmail.com,Antonietta.Nance@gmail.com,doctor\n 14,Carmela,Jefferey,Carmela.Jefferey@yopmail.com,Carmela.Jefferey@gmail.com,developer\n 15,Ebonee,Shields,Ebonee.Shields@yopmail.com,Ebonee.Shields@gmail.com,firefighter\n 16,Allis,Norvol,Allis.Norvol@yopmail.com,Allis.Norvol@gmail.com,police officer\n 17,Mireielle,Ahab,Mireielle.Ahab@yopmail.com,Mireielle.Ahab@gmail.com,doctor\n 18,Tracey,Laverne,Tracey.Laverne@yopmail.com,Tracey.Laverne@gmail.com,doctor\n 19,Robinia,Autrey,Robinia.Autrey@yopmail.com,Robinia.Autrey@gmail.com,police officer\n 20,Imojean,Alarise,Imojean.Alarise@yopmail.com,Imojean.Alarise@gmail.com,police officer\n 21,Basia,Leler,Basia.Leler@yopmail.com,Basia.Leler@gmail.com,developer\n 22,Maryellen,Kylander,Maryellen.Kylander@yopmail.com,Maryellen.Kylander@gmail.com,police officer\n 23,Rivalee,Heidt,Rivalee.Heidt@yopmail.com,Rivalee.Heidt@gmail.com,firefighter\n 24,Barbi,Shanley,Barbi.Shanley@yopmail.com,Barbi.Shanley@gmail.com,doctor\n 25,Lilith,Old,Lilith.Old@yopmail.com,Lilith.Old@gmail.com,developer\n 26,Caressa,Rolf,Caressa.Rolf@yopmail.com,Caressa.Rolf@gmail.com,developer\n 27,Misha,Toni,Misha.Toni@yopmail.com,Misha.Toni@gmail.com,doctor\n 28,Elena,Douglass,Elena.Douglass@yopmail.com,Elena.Douglass@gmail.com,firefighter\n 29,Liana,Kiersten,Liana.Kiersten@yopmail.com,Liana.Kiersten@gmail.com,police officer\n 30,Tera,Dalli,Tera.Dalli@yopmail.com,Tera.Dalli@gmail.com,police officer\n 31,Catrina,Behre,Catrina.Behre@yopmail.com,Catrina.Behre@gmail.com,police officer\n 32,Carmela,Douglass,Carmela.Douglass@yopmail.com,Carmela.Douglass@gmail.com,worker\n 33,Kathy,Sidonius,Kathy.Sidonius@yopmail.com,Kathy.Sidonius@gmail.com,worker\n 34,Nerta,Monk,Nerta.Monk@yopmail.com,Nerta.Monk@gmail.com,doctor\n 35,Shirlee,Mata,Shirlee.Mata@yopmail.com,Shirlee.Mata@gmail.com,police officer\n 36,Joane,Tybald,Joane.Tybald@yopmail.com,Joane.Tybald@gmail.com,police officer\n 37,Flo,Sheedy,Flo.Sheedy@yopmail.com,Flo.Sheedy@gmail.com,doctor\n 38,Concettina,Libna,Concettina.Libna@yopmail.com,Concettina.Libna@gmail.com,firefighter\n 39,Petronia,Middleton,Petronia.Middleton@yopmail.com,Petronia.Middleton@gmail.com,firefighter\n 40,Sissy,Sammons,Sissy.Sammons@yopmail.com,Sissy.Sammons@gmail.com,police officer\n 41,Paulita,Isidore,Paulita.Isidore@yopmail.com,Paulita.Isidore@gmail.com,worker\n 42,Deedee,Raychel,Deedee.Raychel@yopmail.com,Deedee.Raychel@gmail.com,worker\n 43,Cathyleen,Ivens,Cathyleen.Ivens@yopmail.com,Cathyleen.Ivens@gmail.com,developer\n 44,Kaia,Adlare,Kaia.Adlare@yopmail.com,Kaia.Adlare@gmail.com,worker\n 45,Romona,Rossner,Romona.Rossner@yopmail.com,Romona.Rossner@gmail.com,worker\n 46,Fanny,Faro,Fanny.Faro@yopmail.com,Fanny.Faro@gmail.com,worker\n 47,Genovera,Hamil,Genovera.Hamil@yopmail.com,Genovera.Hamil@gmail.com,developer\n 48,Randa,Maribeth,Randa.Maribeth@yopmail.com,Randa.Maribeth@gmail.com,worker\n 49,Claresta,Larochelle,Claresta.Larochelle@yopmail.com,Claresta.Larochelle@gmail.com,worker\n 50,Rani,Olin,Rani.Olin@yopmail.com,Rani.Olin@gmail.com,firefighter\n 51,Dulcinea,Erskine,Dulcinea.Erskine@yopmail.com,Dulcinea.Erskine@gmail.com,worker\n 52,Doro,Camden,Doro.Camden@yopmail.com,Doro.Camden@gmail.com,firefighter\n 53,Winny,Engdahl,Winny.Engdahl@yopmail.com,Winny.Engdahl@gmail.com,firefighter\n 54,Linet,Modie,Linet.Modie@yopmail.com,Linet.Modie@gmail.com,police officer\n 55,Tatiania,Peti,Tatiania.Peti@yopmail.com,Tatiania.Peti@gmail.com,doctor\n 56,Daune,Elephus,Daune.Elephus@yopmail.com,Daune.Elephus@gmail.com,police officer\n 57,Olwen,Seagraves,Olwen.Seagraves@yopmail.com,Olwen.Seagraves@gmail.com,police officer\n 58,Binny,Merna,Binny.Merna@yopmail.com,Binny.Merna@gmail.com,police officer\n 59,Darlleen,Hubert,Darlleen.Hubert@yopmail.com,Darlleen.Hubert@gmail.com,doctor\n 60,June,Bouchard,June.Bouchard@yopmail.com,June.Bouchard@gmail.com,firefighter\n 61,Karly,Turne,Karly.Turne@yopmail.com,Karly.Turne@gmail.com,doctor\n 62,Lynde,Eldrid,Lynde.Eldrid@yopmail.com,Lynde.Eldrid@gmail.com,developer\n 63,Deloria,Ardeha,Deloria.Ardeha@yopmail.com,Deloria.Ardeha@gmail.com,police officer\n 64,Cassandra,Fabiola,Cassandra.Fabiola@yopmail.com,Cassandra.Fabiola@gmail.com,doctor\n 65,Blake,Edee,Blake.Edee@yopmail.com,Blake.Edee@gmail.com,worker\n 66,Julieta,Decato,Julieta.Decato@yopmail.com,Julieta.Decato@gmail.com,developer\n 67,Yolane,Lubin,Yolane.Lubin@yopmail.com,Yolane.Lubin@gmail.com,developer\n 68,Averyl,Duwalt,Averyl.Duwalt@yopmail.com,Averyl.Duwalt@gmail.com,firefighter\n 69,Meriel,Ovid,Meriel.Ovid@yopmail.com,Meriel.Ovid@gmail.com,doctor\n 70,Cacilie,Jotham,Cacilie.Jotham@yopmail.com,Cacilie.Jotham@gmail.com,developer\n 71,Lorne,Schalles,Lorne.Schalles@yopmail.com,Lorne.Schalles@gmail.com,developer\n 72,Adriana,Suzetta,Adriana.Suzetta@yopmail.com,Adriana.Suzetta@gmail.com,worker\n 73,Annabela,Ogren,Annabela.Ogren@yopmail.com,Annabela.Ogren@gmail.com,doctor\n 74,Lulita,Voletta,Lulita.Voletta@yopmail.com,Lulita.Voletta@gmail.com,worker\n 75,Rosaline,Nerita,Rosaline.Nerita@yopmail.com,Rosaline.Nerita@gmail.com,police officer\n 76,Minne,Florina,Minne.Florina@yopmail.com,Minne.Florina@gmail.com,firefighter\n 77,Genovera,Warthman,Genovera.Warthman@yopmail.com,Genovera.Warthman@gmail.com,firefighter\n 78,Sonni,Eachern,Sonni.Eachern@yopmail.com,Sonni.Eachern@gmail.com,firefighter\n 79,Kassey,Daniele,Kassey.Daniele@yopmail.com,Kassey.Daniele@gmail.com,worker\n 80,Annabela,Felizio,Annabela.Felizio@yopmail.com,Annabela.Felizio@gmail.com,firefighter\n 81,Ingrid,Weinreb,Ingrid.Weinreb@yopmail.com,Ingrid.Weinreb@gmail.com,firefighter\n 82,Fawne,Dreda,Fawne.Dreda@yopmail.com,Fawne.Dreda@gmail.com,worker\n 83,Vonny,Ezar,Vonny.Ezar@yopmail.com,Vonny.Ezar@gmail.com,firefighter\n 84,Janenna,Pattin,Janenna.Pattin@yopmail.com,Janenna.Pattin@gmail.com,police officer\n 85,Modestia,Truc,Modestia.Truc@yopmail.com,Modestia.Truc@gmail.com,firefighter\n 86,Brandise,Oster,Brandise.Oster@yopmail.com,Brandise.Oster@gmail.com,worker\n 87,Averyl,Daniele,Averyl.Daniele@yopmail.com,Averyl.Daniele@gmail.com,developer\n 88,Tamqrah,Hedve,Tamqrah.Hedve@yopmail.com,Tamqrah.Hedve@gmail.com,police officer\n 89,Brana,Sharl,Brana.Sharl@yopmail.com,Brana.Sharl@gmail.com,doctor\n 90,Lorenza,Lory,Lorenza.Lory@yopmail.com,Lorenza.Lory@gmail.com,doctor\n 91,Jennica,Tybald,Jennica.Tybald@yopmail.com,Jennica.Tybald@gmail.com,worker\n 92,Desirae,Pacorro,Desirae.Pacorro@yopmail.com,Desirae.Pacorro@gmail.com,police officer\n 93,Deedee,Zitvaa,Deedee.Zitvaa@yopmail.com,Deedee.Zitvaa@gmail.com,worker\n 94,Tori,Allare,Tori.Allare@yopmail.com,Tori.Allare@gmail.com,developer\n 95,Aimil,Schroth,Aimil.Schroth@yopmail.com,Aimil.Schroth@gmail.com,worker\n 96,Blinni,Creamer,Blinni.Creamer@yopmail.com,Blinni.Creamer@gmail.com,doctor\n 97,Jackie,Ledah,Jackie.Ledah@yopmail.com,Jackie.Ledah@gmail.com,doctor\n 98,Genevra,Peg,Genevra.Peg@yopmail.com,Genevra.Peg@gmail.com,developer\n 99,Kirstin,Lytton,Kirstin.Lytton@yopmail.com,Kirstin.Lytton@gmail.com,developer\n 100,Jemie,Francene,Jemie.Francene@yopmail.com,Jemie.Francene@gmail.com,worker\n \n \n`;

const inBetweenNewLineString = `id,firstname,lastname,email,email2,profession\n 1,Rosanne,Fancie,Rosanne.Fancie@yopmail.com,Rosanne.Fancie@gmail.com,firefighter\n 2,Elsie,Mathilde,Elsie.Mathilde@yopmail.com,Elsie.Mathilde@gmail.com,firefighter\n 3,Britni,Si,Britni.Si@yopmail.com,Britni.Si@gmail.com,police officer\n 4,Brynna,Warthman,Brynna.Warthman@yopmail.com,Brynna.Warthman@gmail.com,worker\n 5,Nessie,Septima,Nessie.Septima@yopmail.com,Nessie.Septima@gmail.com,doctor\n 6,Tina,Rona,Tina.Rona@yopmail.com,Tina.Rona@gmail.com,developer\n 7,Dania,Thad,Dania.Thad@yopmail.com,Dania.Thad@gmail.com,firefighter\n\n\n\n 8,Genevra,Susannah,Genevra.Susannah@yopmail.com,Genevra.Susannah@gmail.com,police officer\n 9,Ivett,Alexandr,Ivett.Alexandr@yopmail.com,Ivett.Alexandr@gmail.com,police officer\n 10,Mady,Chrystel,Mady.Chrystel@yopmail.com,Mady.Chrystel@gmail.com,doctor\n`;

const missingComaString = `id,firstname,lastname,email,email2,profession\n 1,Rosanne,FancieRosanne.Fancie@yopmail.com,Rosanne.Fancie@gmail.com,firefighter\n 2,Elsie,Mathilde,Elsie.Mathilde@yopmail.com,Elsie.Mathilde@gmail.com,firefighter\n`;

const arrayOfCSV = [
  "id,firstname,lastname,email,email2,profession\r",
  "1,Rosanne,Fancie,Rosanne.Fancie@yopmail.com,Rosanne.Fancie@gmail.com,firefighter\r",
  "2,Elsie,Mathilde,Elsie.Mathilde@yopmail.com,Elsie.Mathilde@gmail.com,firefighter\r",
  "3,Britni,Si,Britni.Si@yopmail.com,Britni.Si@gmail.com,police officer\r",
  "4,Brynna,Warthman,Brynna.Warthman@yopmail.com,Brynna.Warthman@gmail.com,worker\r",
  "5,Nessie,Septima,Nessie.Septima@yopmail.com,Nessie.Septima@gmail.com,doctor\r",
  "6,Tina,Rona,Tina.Rona@yopmail.com,Tina.Rona@gmail.com,developer\r",
  "7,Dania,Thad,Dania.Thad@yopmail.com,Dania.Thad@gmail.com,firefighter\r",
  "8,Genevra,Susannah,Genevra.Susannah@yopmail.com,Genevra.Susannah@gmail.com,police officer\r",
  "9,Ivett,Alexandr,Ivett.Alexandr@yopmail.com,Ivett.Alexandr@gmail.com,police officer\r",
  "10,Mady,Chrystel,Mady.Chrystel@yopmail.com,Mady.Chrystel@gmail.com,doctor\r",
  "11,Belinda,Anderea,Belinda.Anderea@yopmail.com,Belinda.Anderea@gmail.com,worker\r",
  "12,Kristan,Gavrila,Kristan.Gavrila@yopmail.com,Kristan.Gavrila@gmail.com,firefighter\r",
  "13,Antonietta,Nance,Antonietta.Nance@yopmail.com,Antonietta.Nance@gmail.com,doctor\r",
  "14,Carmela,Jefferey,Carmela.Jefferey@yopmail.com,Carmela.Jefferey@gmail.com,developer\r",
  "15,Ebonee,Shields,Ebonee.Shields@yopmail.com,Ebonee.Shields@gmail.com,firefighter\r",
  "16,Allis,Norvol,Allis.Norvol@yopmail.com,Allis.Norvol@gmail.com,police officer\r",
  "17,Mireielle,Ahab,Mireielle.Ahab@yopmail.com,Mireielle.Ahab@gmail.com,doctor\r",
  "18,Tracey,Laverne,Tracey.Laverne@yopmail.com,Tracey.Laverne@gmail.com,doctor\r",
  "19,Robinia,Autrey,Robinia.Autrey@yopmail.com,Robinia.Autrey@gmail.com,police officer\r",
  "20,Imojean,Alarise,Imojean.Alarise@yopmail.com,Imojean.Alarise@gmail.com,police officer\r",
  "21,Basia,Leler,Basia.Leler@yopmail.com,Basia.Leler@gmail.com,developer\r",
  "22,Maryellen,Kylander,Maryellen.Kylander@yopmail.com,Maryellen.Kylander@gmail.com,police officer\r",
  "23,Rivalee,Heidt,Rivalee.Heidt@yopmail.com,Rivalee.Heidt@gmail.com,firefighter\r",
  "24,Barbi,Shanley,Barbi.Shanley@yopmail.com,Barbi.Shanley@gmail.com,doctor\r",
  "25,Lilith,Old,Lilith.Old@yopmail.com,Lilith.Old@gmail.com,developer\r",
  "26,Caressa,Rolf,Caressa.Rolf@yopmail.com,Caressa.Rolf@gmail.com,developer\r",
  "27,Misha,Toni,Misha.Toni@yopmail.com,Misha.Toni@gmail.com,doctor\r",
  "28,Elena,Douglass,Elena.Douglass@yopmail.com,Elena.Douglass@gmail.com,firefighter\r",
  "29,Liana,Kiersten,Liana.Kiersten@yopmail.com,Liana.Kiersten@gmail.com,police officer\r",
  "30,Tera,Dalli,Tera.Dalli@yopmail.com,Tera.Dalli@gmail.com,police officer\r",
  "31,Catrina,Behre,Catrina.Behre@yopmail.com,Catrina.Behre@gmail.com,police officer\r",
  "32,Carmela,Douglass,Carmela.Douglass@yopmail.com,Carmela.Douglass@gmail.com,worker\r",
  "33,Kathy,Sidonius,Kathy.Sidonius@yopmail.com,Kathy.Sidonius@gmail.com,worker\r",
  "34,Nerta,Monk,Nerta.Monk@yopmail.com,Nerta.Monk@gmail.com,doctor\r",
  "35,Shirlee,Mata,Shirlee.Mata@yopmail.com,Shirlee.Mata@gmail.com,police officer\r",
  "36,Joane,Tybald,Joane.Tybald@yopmail.com,Joane.Tybald@gmail.com,police officer\r",
  "37,Flo,Sheedy,Flo.Sheedy@yopmail.com,Flo.Sheedy@gmail.com,doctor\r",
  "38,Concettina,Libna,Concettina.Libna@yopmail.com,Concettina.Libna@gmail.com,firefighter\r",
  "39,Petronia,Middleton,Petronia.Middleton@yopmail.com,Petronia.Middleton@gmail.com,firefighter\r",
  "40,Sissy,Sammons,Sissy.Sammons@yopmail.com,Sissy.Sammons@gmail.com,police officer\r",
  "41,Paulita,Isidore,Paulita.Isidore@yopmail.com,Paulita.Isidore@gmail.com,worker\r",
  "42,Deedee,Raychel,Deedee.Raychel@yopmail.com,Deedee.Raychel@gmail.com,worker\r",
  "43,Cathyleen,Ivens,Cathyleen.Ivens@yopmail.com,Cathyleen.Ivens@gmail.com,developer\r",
  "44,Kaia,Adlare,Kaia.Adlare@yopmail.com,Kaia.Adlare@gmail.com,worker\r",
  "45,Romona,Rossner,Romona.Rossner@yopmail.com,Romona.Rossner@gmail.com,worker\r",
  "46,Fanny,Faro,Fanny.Faro@yopmail.com,Fanny.Faro@gmail.com,worker\r",
  "47,Genovera,Hamil,Genovera.Hamil@yopmail.com,Genovera.Hamil@gmail.com,developer\r",
  "48,Randa,Maribeth,Randa.Maribeth@yopmail.com,Randa.Maribeth@gmail.com,worker\r",
  "49,Claresta,Larochelle,Claresta.Larochelle@yopmail.com,Claresta.Larochelle@gmail.com,worker\r",
  "50,Rani,Olin,Rani.Olin@yopmail.com,Rani.Olin@gmail.com,firefighter\r",
  "51,Dulcinea,Erskine,Dulcinea.Erskine@yopmail.com,Dulcinea.Erskine@gmail.com,worker\r",
  "52,Doro,Camden,Doro.Camden@yopmail.com,Doro.Camden@gmail.com,firefighter\r",
  "53,Winny,Engdahl,Winny.Engdahl@yopmail.com,Winny.Engdahl@gmail.com,firefighter\r",
  "54,Linet,Modie,Linet.Modie@yopmail.com,Linet.Modie@gmail.com,police officer\r",
  "55,Tatiania,Peti,Tatiania.Peti@yopmail.com,Tatiania.Peti@gmail.com,doctor\r",
  "56,Daune,Elephus,Daune.Elephus@yopmail.com,Daune.Elephus@gmail.com,police officer\r",
  "57,Olwen,Seagraves,Olwen.Seagraves@yopmail.com,Olwen.Seagraves@gmail.com,police officer\r",
  "58,Binny,Merna,Binny.Merna@yopmail.com,Binny.Merna@gmail.com,police officer\r",
  "59,Darlleen,Hubert,Darlleen.Hubert@yopmail.com,Darlleen.Hubert@gmail.com,doctor\r",
  "60,June,Bouchard,June.Bouchard@yopmail.com,June.Bouchard@gmail.com,firefighter\r",
  "61,Karly,Turne,Karly.Turne@yopmail.com,Karly.Turne@gmail.com,doctor\r",
  "62,Lynde,Eldrid,Lynde.Eldrid@yopmail.com,Lynde.Eldrid@gmail.com,developer\r",
  "63,Deloria,Ardeha,Deloria.Ardeha@yopmail.com,Deloria.Ardeha@gmail.com,police officer\r",
  "64,Cassandra,Fabiola,Cassandra.Fabiola@yopmail.com,Cassandra.Fabiola@gmail.com,doctor\r",
  "65,Blake,Edee,Blake.Edee@yopmail.com,Blake.Edee@gmail.com,worker\r",
  "66,Julieta,Decato,Julieta.Decato@yopmail.com,Julieta.Decato@gmail.com,developer\r",
  "67,Yolane,Lubin,Yolane.Lubin@yopmail.com,Yolane.Lubin@gmail.com,developer\r",
  "68,Averyl,Duwalt,Averyl.Duwalt@yopmail.com,Averyl.Duwalt@gmail.com,firefighter\r",
  "69,Meriel,Ovid,Meriel.Ovid@yopmail.com,Meriel.Ovid@gmail.com,doctor\r",
  "70,Cacilie,Jotham,Cacilie.Jotham@yopmail.com,Cacilie.Jotham@gmail.com,developer\r",
  "71,Lorne,Schalles,Lorne.Schalles@yopmail.com,Lorne.Schalles@gmail.com,developer\r",
  "72,Adriana,Suzetta,Adriana.Suzetta@yopmail.com,Adriana.Suzetta@gmail.com,worker\r",
  "73,Annabela,Ogren,Annabela.Ogren@yopmail.com,Annabela.Ogren@gmail.com,doctor\r",
  "74,Lulita,Voletta,Lulita.Voletta@yopmail.com,Lulita.Voletta@gmail.com,worker\r",
  "75,Rosaline,Nerita,Rosaline.Nerita@yopmail.com,Rosaline.Nerita@gmail.com,police officer\r",
  "76,Minne,Florina,Minne.Florina@yopmail.com,Minne.Florina@gmail.com,firefighter\r",
  "77,Genovera,Warthman,Genovera.Warthman@yopmail.com,Genovera.Warthman@gmail.com,firefighter\r",
  "78,Sonni,Eachern,Sonni.Eachern@yopmail.com,Sonni.Eachern@gmail.com,firefighter\r",
  "79,Kassey,Daniele,Kassey.Daniele@yopmail.com,Kassey.Daniele@gmail.com,worker\r",
  "80,Annabela,Felizio,Annabela.Felizio@yopmail.com,Annabela.Felizio@gmail.com,firefighter\r",
];

const emptyLineArray = [
  "id,firstname,lastname,email,email2,profession\r",
  "1,Rosanne,Fancie,Rosanne.Fancie@yopmail.com,Rosanne.Fancie@gmail.com,firefighter\r",
  "2,Elsie,Mathilde,Elsie.Mathilde@yopmail.com,Elsie.Mathilde@gmail.com,firefighter\r",
  "3,Britni,Si,Britni.Si@yopmail.com,Britni.Si@gmail.com,police officer\r",
  "",
  "",
  "",
];

const emptyLineAtCenterArray = [
  "id,firstname,lastname,email,email2,profession\r",
  "1,Rosanne,Fancie,Rosanne.Fancie@yopmail.com,Rosanne.Fancie@gmail.com,firefighter\r",
  "2,Elsie,Mathilde,Elsie.Mathilde@yopmail.com,Elsie.Mathilde@gmail.com,firefighter\r",
  "20,Imojean,Alarise,Imojean.Alarise@yopmail.com,Imojean.Alarise@gmail.com,police officer\r",
  "21,Basia,Leler,Basia.Leler@yopmail.com,Basia.Leler@gmail.com,developer\r",
  "",
  "22,Maryellen,Kylander,Maryellen.Kylander@yopmail.com,Maryellen.Kylander@gmail.com,police officer\r",
  "23,Rivalee,Heidt,Rivalee.Heidt@yopmail.com,Rivalee.Heidt@gmail.com,firefighter\r",
];
const arrayComaRemovedBetween = [
  "id,firstname,lastname,email,email2,profession\r",
  "1,Rosanne,Fancie,Rosanne.Fancie@yopmail.com,Rosanne.Fancie@gmail.com,firefighter\r",
  "2,Elsie,Mathilde,Elsie.Mathilde@yopmail.comElsie.Mathilde@gmail.com,firefighter\r",
  "3,Britni,Si,Britni.Si@yopmail.com,Britni.Si@gmail.com,police officer\r",
];

const twoDArray = [
  ["id", "firstname", "lastname", "email", "email2", "profession"],
  [
    "1",
    "Rosanne",
    "Fancie",
    "mailto:Rosanne.Fancie@yopmail.com",
    "mailto:Rosanne.Fancie@gmail.com",
    "firefighter",
  ],
  [
    "2",
    "Elsie",
    "Mathilde",
    "mailto:Elsie.Mathilde@yopmail.com",
    "mailto:Elsie.Mathilde@gmail.com",
    "firefighter",
  ],
  [
    "3",
    "Britni",
    "Si",
    "mailto:Britni.Si@yopmail.com",
    "mailto:Britni.Si@gmail.com",
    "police officer",
  ],
];

const locationJSON = [
  {
    "id": 28,
    "age": "(223) 692-6221",
    "gmail": "gmail",
    "profession": "Planning Director",
    "city": "Ulpozi",
    "state": "AZ",
    "country": "NE",
    "latitude": -74.61897,
    "longitude": 152.16858
  },
  {
    "id": 56,
    "age": "(256) 607-7589",
    "gmail": "gmail",
    "profession": "Product Manager",
    "city": "Datmiruf",
    "state": "MS",
    "country": "GH",
    "latitude": 32.46726,
    "longitude": -167.77519
  },
  {
    "id": 28,
    "age": "(968) 927-2942",
    "gmail": "gmail",
    "profession": "Managing Partner",
    "city": "Itzupnir",
    "state": "IN",
    "country": "PS",
    "latitude": -35.68292,
    "longitude": -149.68989
  },
  {
    "id": 53,
    "age": "(835) 202-6550",
    "gmail": "gmail",
    "profession": "Economist",
    "city": "Baurivo",
    "state": "MA",
    "country": "SY",
    "latitude": 35.40762,
    "longitude": -50.90459
  },
  {
    "id": 51,
    "age": "(982) 230-2595",
    "gmail": "gmail",
    "profession": "Podiatrist",
    "city": "Hakebu",
    "state": "HI",
    "country": "BT",
    "latitude": 39.44278,
    "longitude": 104.08914
  },
  {
    "id": 55,
    "age": "(415) 421-4035",
    "gmail": "gmail",
    "profession": "Horticulturist",
    "city": "Pemtifuc",
    "state": "TX",
    "country": "AI",
    "latitude": -16.85713,
    "longitude": 150.94573
  },
  {
    "id": 27,
    "age": "(678) 269-7276",
    "gmail": "gmail",
    "profession": "Graphic Designer",
    "city": "Ajfudgin",
    "state": "OR",
    "country": "WF",
    "latitude": -20.62917,
    "longitude": -138.11785
  },
  {
    "id": 29,
    "age": "(465) 293-2456",
    "gmail": "gmail",
    "profession": "Veterinarian",
    "city": "Olazueb",
    "state": "OK",
    "country": "NR",
    "latitude": -18.61675,
    "longitude": -177.65008
  },
  {
    "id": 46,
    "age": "(428) 386-1779",
    "gmail": "gmail",
    "profession": "Occupational Therapist",
    "city": "Zapafape",
    "state": "DC",
    "country": "AX",
    "latitude": -84.31245,
    "longitude": -13.99792
  },
  {
    "id": 50,
    "age": "(565) 568-3075",
    "gmail": "gmail",
    "profession": "Cruise Director",
    "city": "Kebdedpe",
    "state": "AR",
    "country": "BN",
    "latitude": 14.89197,
    "longitude": 137.12228
  },
  {
    "id": 22,
    "age": "(252) 652-9052",
    "gmail": "gmail",
    "profession": "Agent",
    "city": "Jabmeaj",
    "state": "VA",
    "country": "BJ",
    "latitude": 10.25111,
    "longitude": 97.83933
  },
  {
    "id": 43,
    "age": "(610) 310-6483",
    "gmail": "gmail",
    "profession": "Communications Engineer",
    "city": "Hocacep",
    "state": "CT",
    "country": "ER",
    "latitude": 23.74583,
    "longitude": -176.8554
  },
  {
    "id": 43,
    "age": "(667) 711-4128",
    "gmail": "gmail",
    "profession": "Horticulturist",
    "city": "Jopiapa",
    "state": "TN",
    "country": "CV",
    "latitude": -48.27165,
    "longitude": 99.16163
  },
  {
    "id": 57,
    "age": "(713) 947-8164",
    "gmail": "gmail",
    "profession": "Copyright Attorney",
    "city": "Wesrekcim",
    "state": "VA",
    "country": "UZ",
    "latitude": 4.50603,
    "longitude": -135.29811
  },
  {
    "id": 48,
    "age": "(300) 665-5719",
    "gmail": "gmail",
    "profession": "Golf Club Manager",
    "city": "Ekvuzi",
    "state": "MS",
    "country": "LB",
    "latitude": 30.51015,
    "longitude": -67.60388
  },
  {
    "id": 32,
    "age": "(979) 219-3356",
    "gmail": "gmail",
    "profession": "Entrepreneur",
    "city": "Laposeni",
    "state": "IN",
    "country": "CR",
    "latitude": -79.46682,
    "longitude": 76.19937
  },
  {
    "id": 65,
    "age": "(958) 976-3798",
    "gmail": "gmail",
    "profession": "Program Manager",
    "city": "Vufvavida",
    "state": "NJ",
    "country": "MG",
    "latitude": 66.27611,
    "longitude": 137.29458
  },
  {
    "id": 33,
    "age": "(427) 306-5825",
    "gmail": "gmail",
    "profession": "Day Care Instructor",
    "city": "Boojoja",
    "state": "AK",
    "country": "SO",
    "latitude": 47.63407,
    "longitude": 23.12451
  },
  {
    "id": 34,
    "age": "(815) 533-4746",
    "gmail": "gmail",
    "profession": "Environmental Attorney",
    "city": "Vukabziz",
    "state": "WV",
    "country": "RU",
    "latitude": 26.74604,
    "longitude": -35.87389
  },
  {
    "id": 27,
    "age": "(830) 337-4757",
    "gmail": "gmail",
    "profession": "Pharmacist",
    "city": "Kicubot",
    "state": "ID",
    "country": "NE",
    "latitude": 68.57686,
    "longitude": -165.25638
  }
]

module.exports = {
  employeeJSON,
  CSVString,
  singleLineString,
  multipleNewLineString,
  inBetweenNewLineString,
  missingComaString,
  arrayOfCSV,
  emptyLineArray,
  emptyLineAtCenterArray,
  arrayComaRemovedBetween,
  musicGenreJSONData,
  twoDArray,
  locationJSON
};
